language: node_js
node_js:
  - "0.10"
  - "0.11"
script:
  - npm install -g grunt-cli bower karma
  - $CI_ACTION
env:
  matrix:
  - CI_ACTION="grunt"
  - CI_ACTION="grunt test"
  - CI_ACTION="grunt static"
  - CI_ACTION="grunt pack"
  - CI_ACTION="grunt karma"
  - CI_ACTION="grunt mochacov:travis"
